export const GET_NOTES = "GET_NOTES";
export const GET_NOTES_SUCCESSFULLY = "GET_NOTES_SUCCESSFULLY";
export const SET_NEW_NOTE = "SET_NEW_NOTE";
export const SET_EDIT_NOTE = "SET_EDIT_NOTE";
export const DELETE_EDIT_NOTE = "DELETE_EDIT_NOTE";
